MHealth/Models/Domain/View/BookingViewModel.cs
/**
 * This model contains all attributes to be displayed in the view for BookingView
 *
 * @author Jehezkiel Hardwin Tandijaya
 */
namespace MHealth.Models.Domain.View
{
    public class BookingViewModel
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string StaffId { get; set; }
        public string MRIPostId { get; set; }
        public string UserName { get; set; }
        public string StaffName { get; set; }
        public string UserEmail { get; set; }
        public string StaffEmail { get; set; }
        public int Status { get; set; }
        public DateTime BookingTime { get; set; }

    }
}

MHealth/Controllers/AdminController.cs
using CoreHtmlToImage;
using MHealth.Models.Domain;
using MHealth.Models.Domain.View;
using MHealth.Models.DTO;
using MHealth.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.RenderTree;
using Microsoft.AspNetCore.Mvc;

/**
 * This Controller contains all admin functions
 *
 * @author Jehezkiel Hardwin Tandijaya
 */

namespace MHealth.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        //private readonly ILogger<AdminController> _logger;
        private readonly IAdminRepository _adminRepository;
        private readonly IEmailRepository _emailRepository;
        private readonly IConfiguration _configuration;


        /**
        * Default constructor which creates the object of the Admin.
        *
        * @param    _adminRepository        An Interface of Admin 
        * @param    _emailRepository        An Interface of Email
        * @param    _configuration          A configuration
        */
        public AdminController(IAdminRepository _adminRepository, IEmailRepository _emailRepository, IConfiguration _configuration)
        {
            //this._logger = _logger;
            this._adminRepository = _adminRepository;
            this._emailRepository = _emailRepository;
            this._configuration = _configuration;
        }

        /**
        * Announcement method to get the view of announcement.
        *
        * @return   Announcement View
        */
        public async Task<IActionResult> Announcement()
        {
            try
            {
                var users = await _adminRepository.GetAllUser();
                ViewBag.Users = users.ToList();
                //var viewModel = new BulkEmailViewModel
                //{
                //    Users = users// Initialize as empty
                //};
                return View();
                //return View(new BulkEmailViewModel()
                //{
                //    Users = users.ToList()
                //});
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                TempData["error"] = 1;
                return View();
            }
        }

        /**
        * Announce method to send an announcement to the selected user.
        *
        * @param    model       BulkEmailViewModel
        * @return   True:Index View
        *           False:Announcement View
        */
        [HttpPost]
        public async Task<IActionResult> Announce(BulkEmailViewModel model)
        {
            if (ModelState.IsValid)
            {
                var selectedUsers = await _adminRepository.SelectUser(model);
                Console.WriteLine(selectedUsers);
                foreach (var user in selectedUsers)
                {
                    await _emailRepository.SendEmail(_configuration["AdminEmail"], user.Email, model.Subject, model.Announcement);
                }

                return RedirectToAction(nameof(Index));

            }
            var users = await _adminRepository.GetAllUser();
            ViewBag.Users = users.ToList();
            return View(nameof(Announcement));
        }

        /**
        * Index method to display the admin index.
        *
        * @param    currentPage     an Integer
        * @return   Index View
        */
        public async Task<IActionResult> Index(int currentPage = 1)
        {
            //search = string.IsNullOrEmpty(search) ? "" : search.ToLower();
            var users = await _adminRepository.GetAllUser();
            var totalCount = users.Count();
            int pageSize = 5;
            var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
            List<UserModel> userList = users.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();

            UserPaginationViewModel userData = new UserPaginationViewModel()
            {
                Users = userList,
                CurrentPage = currentPage,
                TotalPages = totalPages,
                PageSize = pageSize
            };
            return View(userData);
        }

        /**
        * Booking method to display the booking list.
        *
        * @param    currentPage     an Integer
        * @return   True:Booking View with data
        *           False:Booking View without data
        */
        public async Task<IActionResult> Booking(int currentPage = 1)
        {
            try
            {
                var bookings = await _adminRepository.GetAllBooking();

                var totalCount = bookings.Count();
                int pageSize = 5;
                var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
                List<BookingViewModel> bookingList = bookings.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();

                BookingPaginationViewModel bookingData = new BookingPaginationViewModel()
                {
                    Bookings = bookingList,
                    CurrentPage = currentPage,
                    TotalPages = totalPages,
                    PageSize = pageSize
                };
                return View(bookingData);
            }
            catch (Exception ex)
            {
                TempData["error"] = "1";
            }
            return View();
        }


        /**
        * Chart method to display the rating chart.
        *
        * @return   Chart View with the average rating each staff
        */
        public async Task<IActionResult> Chart()
        {
            try
            {
                IEnumerable<RatingViewModel> userRating = await _adminRepository.GetAverageRating();

                return View(userRating);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View();
            }
        }


        /**
        * EditUser method to get the information editted user.
        *
        * @param    id      a String
        * @return   True:EditUser View
        *           False:Index View
        */
        public async Task<IActionResult> EditUser(string id)
        {
            UserViewModel userViewModel = await _adminRepository.UserModelToUserViewModel(id);
            if (userViewModel != null)
            {
                return View(userViewModel); // Pass the user data to the view
            }
            //TempData["msg"] = $"User is not found with Id : {id}";
            return RedirectToAction(nameof(Index));
        }

        /**
        * EditUser method to make the changes of user.
        *
        * @param    model      a UserViewModel
        * @return   True:Index View
        *           False:EditUser View
        */
        [HttpPost]
        public async Task<IActionResult> EditUser(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _adminRepository.UpdateUser(model);
                    //TempData["code"] = "1";
                    //TempData["msg"] = "The user updated successfully";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    //TempData["code"] = "0";
                    //TempData["msg"] = "The user is failed to be updated";
                    return View();
                }
            }
            return View();
        }

        /**
        * DeleteUser method to delete the selected user.
        *
        * @param    id      a String
        * @return   Index View
        */
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            try
            {
                UserModel user = await _adminRepository.GetUserById(id);

                if (user != null)
                {
                    try
                    {
                        await _adminRepository.DeleteUser(id);
                        //return RedirectToAction(nameof(Index));

                        //TempData["msg"] = "The user deleted successfully";
                    }
                    catch (Exception ex)
                    {
                        //TempData["msg"] = ex.Message;

                    }

                }
            }
            catch (Exception ex)
            {
                //TempData["msg"] = ex.Message;

            }
            TempData["msg"] = $"User is not found with Id : {id}";
            return RedirectToAction(nameof(Index));

        }

        /**
        * DeleteBooking method to delete the selected booking.
        *
        * @param    id      a String
        * @return   True:Booking View
        */
        [HttpPost]
        public async Task<IActionResult> DeleteBooking(string id)
        {
            try
            {
                BookingModel user = await _adminRepository.GetBookingById(id);

                if (user != null)
                {
                    try
                    {
                        await _adminRepository.DeleteBooking(id);
                        //return RedirectToAction(nameof(Index));

                        //TempData["msg"] = "The user deleted successfully";
                    }
                    catch (Exception ex)
                    {
                        //TempData["msg"] = ex.Message;

                    }

                }
            }
            catch (Exception ex)
            {
                //TempData["msg"] = ex.Message;

            }
            TempData["msg"] = $"Booking is not found with Id : {id}";
            return RedirectToAction(nameof(Booking));

        }

        /**
        * CreateStaff method display the create view.
        *
        * @return  CreateStaff View
        */
        public IActionResult CreateStaff()
        {
            return View();
        }

        [HttpPost]

MHealth/Controllers/StaffController.cs
using MHealth.Migrations;
using MHealth.Models.Domain;
using MHealth.Models.Domain.View;
using MHealth.Models.DTO;
using MHealth.Repositories.Abstract;
using MHealth.Repositories.Implementation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;

/**
 * This Controller contains all staff functions
 *
 * @author Jehezkiel Hardwin Tandijaya
 */
namespace MHealth.Controllers
{
    [Authorize(Roles = "staff")]
    public class StaffController : Controller
    {
        //private readonly ILogger<BookingController> _logger;
        private readonly IStaffRepository _staffRepository;
        private readonly UserManager<UserModel> _userManager;
        private readonly IEmailRepository _emailRepository;

        /**
        * Default constructor which creates the object of the Staff.
        *
        * @param    _staffRepository    An Interface of Staff 
        * @param    _userManager        An Interface of User
        * @param    _emailRepository    An Interface of Email
        */
        public StaffController(IStaffRepository _staffRepository, UserManager<UserModel> _userManager, IEmailRepository _emailRepository)
        {
            //this._logger = _logger;
            this._staffRepository = _staffRepository;
            this._userManager = _userManager;
            this._emailRepository = _emailRepository;
        }

        /**
        * Index method to display the staff index.
        *
        * @param    currentPage     an Integer
        * @return   Index View
        */
        public async Task<IActionResult> Index(int currentPage = 1)
        {
            var user = await _userManager.GetUserAsync(User);
            try
            {
                var bookings = await _staffRepository.GetAllBooking(user.Id);

                var totalCount = bookings.Count();
                int pageSize = 5;
                var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
                List<BookingViewModel> bookingList = bookings.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();

                BookingPaginationViewModel bookingData = new BookingPaginationViewModel()
                {
                    Bookings = bookingList,
                    CurrentPage = currentPage,
                    TotalPages = totalPages,
                    PageSize = pageSize
                };
                return View(bookingData);
            }
            catch (Exception ex)
            {
                TempData["error"] = "1";
            }
            return View();
        }

        /**
        * Detail method to display the detail view.
        *
        * @param    bookingId   a String
        * @param    userId      a String
        * @param    staffId     a String
        * @return   Detail View
        */
        [HttpPost]
        public async Task<IActionResult> Detail(string bookingId, string userId, string staffId)
        {
            UserModel user = await _staffRepository.GetUserInformation(userId);
            ViewBag.UserName = user.UserName;
            var booking = new MRIPostModel()
            {
                BookingId = bookingId,
                UserId = userId,
                StaffId = staffId
            };
            return View(booking);
        }

        /**
        * Post method to post the result of mri.
        *
        * @param    model       a MRIPostModel
        * @param    postImage   an IFormFile
        * @param    description a String
        * @return   True:Index View
        *           False:Detail View
        */
        [HttpPost]
        public async Task<IActionResult> Post(MRIPostModel model, IFormFile postImage, string description)
        {

            if (postImage == null)
            {
                return View(nameof(Detail), new MRIPostModel
                {
                    BookingId = model.BookingId,
                    UserId = model.UserId,
                    StaffId = model.StaffId
                });
            }
            try
            {
                MRIPostModel postModel = await _staffRepository.WriteFile(postImage);

                //Console.WriteLine(fileName);
                model.Description = description;
                model.Id = Guid.NewGuid().ToString();
                //Console.WriteLine(fileName.ToString());
                model.PostPath = postModel.PostPath.ToString();

                await _staffRepository.Post(model);
                Console.WriteLine(model.BookingId);
                var bookingDetail = await _staffRepository.GetBookingDetail(model.BookingId);
                await _emailRepository.SendEmail(bookingDetail.StaffEmail, bookingDetail.UserEmail, "MRI RESULT", description, model.PostPath);

                //return View(model);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(nameof(Detail), new MRIPostModel
                {
                    BookingId = model.BookingId,
                    UserId = model.UserId,
                    StaffId = model.StaffId
                });
            }
        }
    }
}

MHealth/Views/Admin/Announce.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@Model.Announcement

MHealth/Views/Admin/Announcement.cshtml
@using MHealth.Models.Domain.View;
@model BulkEmailViewModel;
@{
    ViewData["Title"] = "Announcement";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h5 class="mt-3">@ViewData["Title"]</h5>

@if(TempData["error"] != "1")
{
<div class="row mt-3">
    <div class="col-md-8 col-lg-6">
        <form asp-action="Announce" asp-controller="Admin" method="post">
            <div class="form-group">
                <label asp-for="Subject" class="control-label">Subject:</label>
                <input type="text" asp-for="Subject" class="form-control"></input>
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Announcement" class="control-label">Announcement:</label>
                <textarea asp-for="Announcement" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Announcement" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="SelectedUserIds" class="control-label">Select Users:</label>

                    <select name="SelectedUserIds" class="form-control" multiple>
                        @foreach (var user in ViewBag.Users)
                        {
                            <option value="@user.Id">@user.UserName</option>
                        }
                    </select>
                <span asp-validation-for="SelectedUserIds" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary mt-3">Post</button>
        </form>
    </div>
</div>
}

MHealth/Views/Admin/Booking.cshtml
@{
    ViewData["Title"] = "Booking";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    string[] TableHeaders = new string[]
    {
    "UserName",
    "StaffName",
    "BookingTime",
    "Actions"
    };
}

<h5 class="mt-3">@ViewData["Title"]</h5>


@if (TempData["error"] == "1")
{
    <p>No Data Exist!</p>
}
else
{
    <div class="row mt-3">
        <div class="col-md-12">
            <table class="table bg-white rounded shadow-sm  table-hover">
                <thead>
                    <tr>
                        @foreach (var header in TableHeaders)
                        {
                            <th>
                                @header
                            </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var Data in Model.Bookings)
                        {
                            <tr>
                                <td>@Data.UserName</td>
                                <td>@Data.StaffName</td>
                                <td>@Data.BookingTime</td>
                                <td>

                                    <div class="btn-group btn-group-md">
                                        @*<form asp-controller="Staff" asp-action="Detail" method="post" asp-route-id="@Data.Id">*@
                                        <form asp-controller="Admin" asp-action="DeleteBooking" method="post" asp-route-id="@Data.Id">
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </div>

                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    @if (Model.CurrentPage != 1)
                    {
                        <li class="page-item"><a class="page-link" href="?currentPage=@(Model.CurrentPage-1)">Previous</a></li>

                    }
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        if (i == Model.CurrentPage)
                        {
                            <li class="page-item"><a class="page-link active" href="?currentPage=@i">@i</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="?currentPage=@i">@i</a></li>
                        }
                    }
                    @if (Model.CurrentPage < Model.TotalPages)
                    {
                        <li class="page-item"><a class="page-link" href="?currentPage=@(Model.CurrentPage+1)">Next</a></li>
                    }
                </ul>
            </nav>
        </div>
    </div>
}

MHealth/Views/Admin/Chart.cshtml
@{
    ViewData["Title"] = "Chart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    string[] TableHeaders = new string[]
    {
    "StaffName",
    "Rating"
    };

    List<string> staffNames = new List<string>();
    List<double> averageRatings = new List<double>();

    foreach (var Data in Model)
    {
        // Populate the arrays with staff names and average ratings
        staffNames.Add(Data.StaffName);
        averageRatings.Add(Data.AverageRating);
    }
}

<h5 class="mt-3">@ViewData["Title"]</h5>

<div class="row mt-3">
    <div class="col-md-12">
        <div class="row">
            <div class="column-md-12">
                <div>
                    <canvas id="myChart"></canvas>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <button type="submit" class="btn btn-primary mt-3" asp-action="GeneratePDF" asp-controller="Admin">PDF</button>
                    @*<button type="submit" class="btn btn-primary mt-3" asp-action="GenerateJPG" asp-controller="Admin">JPG</button>*@
                </form>
            </div>
        </div>
    </div>
</div>






<div class="row mt-3">
    <div class="col-md-12">
        <table class="table bg-white rounded shadow-sm  table-hover">
            <thead>
                <tr>
                    @foreach (var header in TableHeaders)
                    {
                        <th>
                            @header
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var Data in Model)
                    {
                        <tr>
                            <td>@Data.StaffName</td>
                            <td>@Data.AverageRating</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    const staffNames = @Html.Raw(Json.Serialize(staffNames)); // Serialize the staffNames list to JavaScript
    const averageRatings = @Html.Raw(Json.Serialize(averageRatings))

    const ctx = document.getElementById('myChart');

    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: staffNames,
            datasets: [{
                label: '# of Ratings',
                data: averageRatings,
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>

MHealth/Views/Admin/CreateStaff.cshtml
@model MHealth.Models.DTO.SignupModel
@{
    ViewData["Title"] = "Signup as a Staff";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h5 class="mt-3">@ViewData["Title"]</h5>

<div class="row">
    <div class="col-md-8 col-lg-6">
        <form asp-action="CreateStaff" asp-controller="Admin" method="post">
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Username">Username</label>
                <input type="text" class="form-control" asp-for="Username" placeholder="Username">
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input type="text" class="form-control" asp-for="Email" placeholder="Email">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password">Password</label>
                <input type="password" class="form-control" asp-for="Password" placeholder="Password">
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordConfirm">Password Confirm</label>
                <input type="password" class="form-control" asp-for="PasswordConfirm" placeholder="Password Confirm">
                <span asp-validation-for="PasswordConfirm" class="text-danger"></span>
            </div>
            @*@if (TempData["msg"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["msg"]
                </div>
            }*@
            <button type="submit" class="btn btn-primary mt-3">Create Staff</button>
            <a asp-action="index" asp-controller="Admin" class="btn btn-success ml-3 mt-3">Back</a>
        </form>
    </div>
</div>

MHealth/Views/Admin/EditUser.cshtml
@using MHealth.Models.Domain;
@model UserViewModel;
@{
    ViewData["Title"] = "Edit User";
    ViewData["Menu"] = "Edit User";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h5 class="mt-3">@ViewData["Title"]</h5>

<form asp-controller="Admin" asp-action="EditUser" method="post">
<div class="row">
    <div class="col-md-8 col-lg-6">
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input type="text" class="form-control" asp-for="Name" placeholder="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="UserName">Username</label>
            <input type="text" class="form-control" asp-for="UserName" placeholder="Username">
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email">Email</label>
            <input type="text" class="form-control" asp-for="Email" placeholder="Email">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        @*@if (TempData["msg"] != null)
        {
            <div class="alert alert-danger" role="alert">
                @TempData["msg"]
            </div>
        }*@
        <button type="submit" class="btn btn-primary mt-3">Edit User</button>
        <a asp-action="Index" asp-asp-controller="Admin" class="btn btn-success ml-3 mt-3">Back</a>
    </div>
</div>
</form>

MHealth/Views/Admin/GeneratedChart.cshtml
@{
    ViewData["Title"] = "Chart";
    string[] TableHeaders = new string[]
    {
    "StaffName",
    "Rating"
    };

    List<string> staffNames = new List<string>();
    List<double> averageRatings = new List<double>();

    foreach (var Data in Model)
    {
        // Populate the arrays with staff names and average ratings
        staffNames.Add(Data.StaffName);
        averageRatings.Add(Data.AverageRating);
    }
}

<h5 class="mt-3">@ViewData["Title"]</h5>

<div class="row mt-3">
    <div class="col-md-12">
        <div class="row">
            <div class="column-md-12">
                <div>
                    <canvas id="myChart"></canvas>
                </div>
            </div>
        </div>


    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    const staffNames = @Html.Raw(Json.Serialize(staffNames)); // Serialize the staffNames list to JavaScript
    const averageRatings = @Html.Raw(Json.Serialize(averageRatings))

    const ctx = document.getElementById('myChart');

    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: staffNames,
            datasets: [{
                label: '# of Ratings',
                data: averageRatings,
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>