MHealth/Controllers/AdminController.cs
using CoreHtmlToImage;
using MHealth.Models.Domain;
using MHealth.Models.Domain.View;
using MHealth.Models.DTO;
using MHealth.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.RenderTree;
using Microsoft.AspNetCore.Mvc;

/**
 * This Controller contains all admin functions
 *
 * @author Jehezkiel Hardwin Tandijaya
 */

namespace MHealth.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        //private readonly ILogger<AdminController> _logger;
        private readonly IAdminRepository _adminRepository;
        private readonly IEmailRepository _emailRepository;
        private readonly IConfiguration _configuration;


        /**
        * Default constructor which creates the object of the Admin.
        *
        * @param    _adminRepository        An Interface of Admin 
        * @param    _emailRepository        An Interface of Email
        * @param    _configuration          A configuration
        */
        public AdminController(IAdminRepository _adminRepository, IEmailRepository _emailRepository, IConfiguration _configuration)
        {
            //this._logger = _logger;
            this._adminRepository = _adminRepository;
            this._emailRepository = _emailRepository;
            this._configuration = _configuration;
        }

        /**
        * Announcement method to get the view of announcement.
        *
        * @return   Announcement View
        */
        public async Task<IActionResult> Announcement()
        {
            try
            {
                var users = await _adminRepository.GetAllUser();
                ViewBag.Users = users.ToList();
                //var viewModel = new BulkEmailViewModel
                //{
                //    Users = users// Initialize as empty
                //};
                return View();
                //return View(new BulkEmailViewModel()
                //{
                //    Users = users.ToList()
                //});
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                TempData["error"] = 1;
                return View();
            }
        }

        /**
        * Announce method to send an announcement to the selected user.
        *
        * @param    model       BulkEmailViewModel
        * @return   True:Index View
        *           False:Announcement View
        */
        [HttpPost]
        public async Task<IActionResult> Announce(BulkEmailViewModel model)
        {
            if (ModelState.IsValid)
            {
                var selectedUsers = await _adminRepository.SelectUser(model);
                Console.WriteLine(selectedUsers);
                foreach (var user in selectedUsers)
                {
                    await _emailRepository.SendEmail(_configuration["AdminEmail"], user.Email, model.Subject, model.Announcement);
                }

                return RedirectToAction(nameof(Index));

            }
            var users = await _adminRepository.GetAllUser();
            ViewBag.Users = users.ToList();
            return View(nameof(Announcement));
        }

        /**
        * Index method to display the admin index.
        *
        * @param    currentPage     an Integer
        * @return   Index View
        */
        public async Task<IActionResult> Index(int currentPage = 1)
        {
            //search = string.IsNullOrEmpty(search) ? "" : search.ToLower();
            var users = await _adminRepository.GetAllUser();
            var totalCount = users.Count();
            int pageSize = 5;
            var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
            List<UserModel> userList = users.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();

            UserPaginationViewModel userData = new UserPaginationViewModel()
            {
                Users = userList,
                CurrentPage = currentPage,
                TotalPages = totalPages,
                PageSize = pageSize
            };
            return View(userData);
        }

        /**
        * Booking method to display the booking list.
        *
        * @param    currentPage     an Integer
        * @return   True:Booking View with data
        *           False:Booking View without data
        */
        public async Task<IActionResult> Booking(int currentPage = 1)
        {
            try
            {
                var bookings = await _adminRepository.GetAllBooking();

                var totalCount = bookings.Count();
                int pageSize = 5;
                var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
                List<BookingViewModel> bookingList = bookings.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();

                BookingPaginationViewModel bookingData = new BookingPaginationViewModel()
                {
                    Bookings = bookingList,
                    CurrentPage = currentPage,
                    TotalPages = totalPages,
                    PageSize = pageSize
                };
                return View(bookingData);
            }
            catch (Exception ex)
            {
                TempData["error"] = "1";
            }
            return View();
        }


        /**
        * Chart method to display the rating chart.
        *
        * @return   Chart View with the average rating each staff
        */
        public async Task<IActionResult> Chart()
        {
            try
            {
                IEnumerable<RatingViewModel> userRating = await _adminRepository.GetAverageRating();

                return View(userRating);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View();
            }
        }


        /**
        * EditUser method to get the information editted user.
        *
        * @param    id      a String
        * @return   True:EditUser View
        *           False:Index View
        */
        public async Task<IActionResult> EditUser(string id)
        {
            UserViewModel userViewModel = await _adminRepository.UserModelToUserViewModel(id);
            if (userViewModel != null)
            {
                return View(userViewModel); // Pass the user data to the view
            }
            //TempData["msg"] = $"User is not found with Id : {id}";
            return RedirectToAction(nameof(Index));
        }

        /**
        * EditUser method to make the changes of user.
        *
        * @param    model      a UserViewModel
        * @return   True:Index View
        *           False:EditUser View
        */
        [HttpPost]
        public async Task<IActionResult> EditUser(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _adminRepository.UpdateUser(model);
                    //TempData["code"] = "1";
                    //TempData["msg"] = "The user updated successfully";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    //TempData["code"] = "0";
                    //TempData["msg"] = "The user is failed to be updated";
                    return View();
                }
            }
            return View();
        }

        /**
        * DeleteUser method to delete the selected user.
        *
        * @param    id      a String
        * @return   Index View
        */
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            try
            {
                UserModel user = await _adminRepository.GetUserById(id);

                if (user != null)
                {
                    try
                    {
                        await _adminRepository.DeleteUser(id);
                        //return RedirectToAction(nameof(Index));

                        //TempData["msg"] = "The user deleted successfully";
                    }
                    catch (Exception ex)
                    {
                        //TempData["msg"] = ex.Message;

                    }

                }
            }
            catch (Exception ex)
            {
                //TempData["msg"] = ex.Message;

            }
            TempData["msg"] = $"User is not found with Id : {id}";
            return RedirectToAction(nameof(Index));

        }

        /**
        * DeleteBooking method to delete the selected booking.
        *
        * @param    id      a String
        * @return   True:Booking View
        */
        [HttpPost]
        public async Task<IActionResult> DeleteBooking(string id)
        {
            try
            {
                BookingModel user = await _adminRepository.GetBookingById(id);

                if (user != null)
                {
                    try
                    {
                        await _adminRepository.DeleteBooking(id);
                        //return RedirectToAction(nameof(Index));

                        //TempData["msg"] = "The user deleted successfully";
                    }
                    catch (Exception ex)
                    {
                        //TempData["msg"] = ex.Message;

                    }

                }
            }
            catch (Exception ex)
            {
                //TempData["msg"] = ex.Message;

            }
            TempData["msg"] = $"Booking is not found with Id : {id}";
            return RedirectToAction(nameof(Booking));

        }

        /**
        * CreateStaff method display the create view.
        *
        * @return  CreateStaff View
        */
        public IActionResult CreateStaff()
        {
            return View();
        }

        [HttpPost]

MHealth/Controllers/LocationController.cs
using Microsoft.AspNetCore.Mvc;

/**
 * This Controller contains all location functions
 *
 * @author Jehezkiel Hardwin Tandijaya
 */
namespace MHealth.Controllers
{
    public class LocationController : Controller
    {
        private readonly IConfiguration _configuration;

        /**
        * Default constructor which creates the object of the Location.
        *
        * @param    _configuration          A configuration
        */
        public LocationController(IConfiguration configuration)
        {
            _configuration = configuration;
        }


        /**
        * Index method to display the location.
        *
        * @return   Index View
        */
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

MHealth/Views/Shared/_AdminLayout.cshtml
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MHealth</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/adminstyle.css" asp-append-version="true" />

</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom">
                <a asp-action="Index" asp-controller="Admin" style="color: black;text-decoration: none;"><i class="fas fa-user-secret me-2"></i>MHealth</a>
            </div>
            <div class="list-group list-group-flush my-3">
                @*<a asp-action="Staff" asp-controller="Admin" class="list-group-item list-group-item-action bg-transparent text-secondary fw-bold">
                    <i class="fas fa-project-diagram me-2"></i>Staff
                </a>*@
                <a asp-action="Chart" asp-controller="Admin" class="list-group-item list-group-item-action bg-transparent text-secondary fw-bold">
                    <i class="fas fa-chart-line me-2"></i>Chart
                </a>
                <a asp-action="Announcement" asp-controller="Admin" class="list-group-item list-group-item-action bg-transparent text-secondary fw-bold">
                    <i class="fas fa-project-diagram me-2"></i>Make an announcement
                </a>
                <a asp-action="Booking" asp-controller="Admin" class="list-group-item list-group-item-action bg-transparent text-secondary fw-bold">
                    <i class="fas fa-project-diagram me-2"></i>Booking
                </a>
                
                <a asp-controller="User" asp-action="Logout" class="list-group-item list-group-item-action bg-transparent text-danger fw-bold">
                    <i class="fas fa-chart-line me-2"></i>Logout
                </a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
                <div class="d-flex align-items-center">
                    <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                    <h2 class="fs-2 m-0">@ViewData["Menu"]</h2>
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle second-text fw-bold" href="#" id="navbarDropdown"
                               role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user me-2"></i>admin
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <!--<li><a class="dropdown-item" href="#">Profile</a></li>
                                <li><a class="dropdown-item" href="#">Settings</a></li>-->
                                <li><a class="dropdown-item" asp-controller="User" asp-action="Logout">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container-fluid px-4 mb-3">
                @RenderBody()

            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script>
    @*@await RenderSectionAsync("Scripts", required: false)*@
</body>
</html>

MHealth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MHealth</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Include Bootstrap Datepicker CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/css/bootstrap-datepicker.min.css" />

    @*MAP*@
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <a class="navbar-brand ml-3" asp-area="" asp-controller="Home" asp-action="Index">MHealth</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between px-5" id="navbarNav">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Location" asp-action="Index">Location</a>
                </li>
                @if (!User.IsInRole("staff"))
                {
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="Services" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Services
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="Services">
                            @*<li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>*@

                            <li>@Html.ActionLink("MRI", "Staff", "Home", new { area = "" }, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                }
                <!-- End of Dropdown -->
                @*<li>@Html.ActionLink("Doctor", "Staff", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
            </ul>
            @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("admin"))
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="Index">Dashboard</a>
                        </li>
                    </ul>
                }
                else if (User.IsInRole("staff"))
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Staff" asp-action="Index">My Patient</a>
                        </li>
                    </ul>
                }
                else if (User.IsInRole("user"))
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Booking" asp-action="Index">My Booking</a>
                        </li>
                    </ul>
                }
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="User" asp-action="Logout">LogOut</a>
                    </li>
                </ul>
            }
            else
            {
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="User" asp-action="Login">Login</a>
                    </li>
                </ul>
            }
        </div>
    </nav>

    <div class="container-fluid">
        @RenderBody()
    </div>

    <!-- Include jQuery and Bootstrap JavaScript -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Include Bootstrap Datepicker JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/js/bootstrap-datepicker.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js"></script>


    @*<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZP8zlrrkzeJfpo9RKOL6NoNMghN_wRQQ&callback=initMap"></script>*@
    
</body>
</html>